# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FIITM.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FIITM(object):
    def setupUi(self, FIITM):
        FIITM.setObjectName("FIITM")
        FIITM.resize(1062, 789)
        self.centralwidget = QtWidgets.QWidget(FIITM)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(373, 13, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 3, 1)
        spacerItem1 = QtWidgets.QSpacerItem(10, 225, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 4, 5, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 4, 1, 1)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(1, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 0, 2, 1, 1)
        self.RunDC_BT = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(11)
        self.RunDC_BT.setFont(font)
        self.RunDC_BT.setObjectName("RunDC_BT")
        self.gridLayout_2.addWidget(self.RunDC_BT, 0, 3, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 0, 4, 1, 1)
        self.PauseDC_BT = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(11)
        self.PauseDC_BT.setFont(font)
        self.PauseDC_BT.setObjectName("PauseDC_BT")
        self.gridLayout_2.addWidget(self.PauseDC_BT, 0, 5, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(1, 18, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 0, 6, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem6, 0, 7, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(1, 18, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem7, 0, 8, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 9, 1, 2)
        spacerItem8 = QtWidgets.QSpacerItem(1, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem8, 0, 11, 1, 1)
        self.RunIC_BT = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(11)
        self.RunIC_BT.setFont(font)
        self.RunIC_BT.setObjectName("RunIC_BT")
        self.gridLayout_2.addWidget(self.RunIC_BT, 0, 12, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem9, 0, 13, 1, 1)
        self.PauseIC_BT = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(11)
        self.PauseIC_BT.setFont(font)
        self.PauseIC_BT.setObjectName("PauseIC_BT")
        self.gridLayout_2.addWidget(self.PauseIC_BT, 0, 14, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(1, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem10, 0, 15, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(1, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem11, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 1, 1, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem12, 1, 2, 1, 1)
        self.SaveVideoStart_BT = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(11)
        self.SaveVideoStart_BT.setFont(font)
        self.SaveVideoStart_BT.setObjectName("SaveVideoStart_BT")
        self.gridLayout_2.addWidget(self.SaveVideoStart_BT, 1, 3, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem13, 1, 4, 1, 1)
        self.SaveVideoStop_BT = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(11)
        self.SaveVideoStop_BT.setFont(font)
        self.SaveVideoStop_BT.setObjectName("SaveVideoStop_BT")
        self.gridLayout_2.addWidget(self.SaveVideoStop_BT, 1, 5, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(1, 18, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem14, 1, 6, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem15, 1, 7, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(1, 18, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem16, 1, 8, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 1, 9, 1, 2)
        spacerItem17 = QtWidgets.QSpacerItem(1, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem17, 1, 11, 1, 1)
        self.AutosaveFramesStart_BT = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(11)
        self.AutosaveFramesStart_BT.setFont(font)
        self.AutosaveFramesStart_BT.setObjectName("AutosaveFramesStart_BT")
        self.gridLayout_2.addWidget(self.AutosaveFramesStart_BT, 1, 12, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem18, 1, 13, 1, 1)
        self.AutosaveFramesStop_BT = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(11)
        self.AutosaveFramesStop_BT.setFont(font)
        self.AutosaveFramesStop_BT.setObjectName("AutosaveFramesStop_BT")
        self.gridLayout_2.addWidget(self.AutosaveFramesStop_BT, 1, 14, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(1, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem19, 1, 15, 1, 1)
        spacerItem20 = QtWidgets.QSpacerItem(1, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem20, 2, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 2, 1, 1, 1)
        spacerItem21 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem21, 2, 2, 1, 1)
        self.SaveFrame_BT = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(11)
        self.SaveFrame_BT.setFont(font)
        self.SaveFrame_BT.setObjectName("SaveFrame_BT")
        self.gridLayout_2.addWidget(self.SaveFrame_BT, 2, 3, 1, 2)
        spacerItem22 = QtWidgets.QSpacerItem(72, 22, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem22, 2, 5, 1, 1)
        spacerItem23 = QtWidgets.QSpacerItem(1, 18, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem23, 2, 6, 1, 1)
        spacerItem24 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem24, 2, 7, 1, 1)
        spacerItem25 = QtWidgets.QSpacerItem(1, 18, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem25, 2, 8, 1, 1)
        spacerItem26 = QtWidgets.QSpacerItem(65, 18, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem26, 2, 9, 1, 1)
        self.InputModeCameras_RBT = QtWidgets.QRadioButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(11)
        self.InputModeCameras_RBT.setFont(font)
        self.InputModeCameras_RBT.setObjectName("InputModeCameras_RBT")
        self.gridLayout_2.addWidget(self.InputModeCameras_RBT, 2, 10, 1, 1)
        spacerItem27 = QtWidgets.QSpacerItem(32, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem27, 2, 11, 1, 1)
        self.InputModeVideos_RBT = QtWidgets.QRadioButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(11)
        self.InputModeVideos_RBT.setFont(font)
        self.InputModeVideos_RBT.setObjectName("InputModeVideos_RBT")
        self.gridLayout_2.addWidget(self.InputModeVideos_RBT, 2, 12, 1, 1)
        spacerItem28 = QtWidgets.QSpacerItem(32, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem28, 2, 13, 1, 1)
        self.InputModePictures_RBT = QtWidgets.QRadioButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(11)
        self.InputModePictures_RBT.setFont(font)
        self.InputModePictures_RBT.setObjectName("InputModePictures_RBT")
        self.gridLayout_2.addWidget(self.InputModePictures_RBT, 2, 14, 1, 1)
        self.gridLayout.addWidget(self.widget, 5, 1, 1, 4)
        spacerItem29 = QtWidgets.QSpacerItem(10, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem29, 0, 0, 4, 1)
        spacerItem30 = QtWidgets.QSpacerItem(10, 130, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem30, 5, 0, 1, 1)
        self.IC_Window = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.IC_Window.sizePolicy().hasHeightForWidth())
        self.IC_Window.setSizePolicy(sizePolicy)
        self.IC_Window.setFrameShape(QtWidgets.QFrame.Box)
        self.IC_Window.setText("")
        self.IC_Window.setObjectName("IC_Window")
        self.gridLayout.addWidget(self.IC_Window, 4, 4, 1, 1)
        spacerItem31 = QtWidgets.QSpacerItem(10, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem31, 2, 5, 2, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 1, 1, 1)
        spacerItem32 = QtWidgets.QSpacerItem(13, 70, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem32, 6, 0, 1, 1)
        spacerItem33 = QtWidgets.QSpacerItem(10, 225, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem33, 4, 0, 1, 1)
        self.DC_Window = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DC_Window.sizePolicy().hasHeightForWidth())
        self.DC_Window.setSizePolicy(sizePolicy)
        self.DC_Window.setFrameShape(QtWidgets.QFrame.Box)
        self.DC_Window.setText("")
        self.DC_Window.setObjectName("DC_Window")
        self.gridLayout.addWidget(self.DC_Window, 4, 1, 1, 1)
        spacerItem34 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem34, 3, 2, 1, 1)
        spacerItem35 = QtWidgets.QSpacerItem(13, 70, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem35, 6, 5, 1, 1)
        spacerItem36 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem36, 4, 2, 1, 1)
        spacerItem37 = QtWidgets.QSpacerItem(328, 13, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem37, 0, 3, 3, 2)
        spacerItem38 = QtWidgets.QSpacerItem(13, 130, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem38, 5, 5, 1, 1)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem39 = QtWidgets.QSpacerItem(40, 40, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem39)
        self.LogOut_Window = QtWidgets.QPlainTextEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LogOut_Window.sizePolicy().hasHeightForWidth())
        self.LogOut_Window.setSizePolicy(sizePolicy)
        self.LogOut_Window.setObjectName("LogOut_Window")
        self.horizontalLayout.addWidget(self.LogOut_Window)
        spacerItem40 = QtWidgets.QSpacerItem(148, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem40)
        self.Exit_BT = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(12)
        self.Exit_BT.setFont(font)
        self.Exit_BT.setObjectName("Exit_BT")
        self.horizontalLayout.addWidget(self.Exit_BT)
        spacerItem41 = QtWidgets.QSpacerItem(40, 40, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem41)
        self.gridLayout.addWidget(self.frame, 6, 1, 1, 4)
        FIITM.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(FIITM)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1062, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        FIITM.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(FIITM)
        self.statusbar.setObjectName("statusbar")
        FIITM.setStatusBar(self.statusbar)
        self.actionOpen_DCPicture = QtWidgets.QAction(FIITM)
        self.actionOpen_DCPicture.setObjectName("actionOpen_DCPicture")
        self.actionOpen_DCVideo = QtWidgets.QAction(FIITM)
        self.actionOpen_DCVideo.setObjectName("actionOpen_DCVideo")
        self.actionSave_Log = QtWidgets.QAction(FIITM)
        self.actionSave_Log.setObjectName("actionSave_Log")
        self.actionSave_Settings = QtWidgets.QAction(FIITM)
        self.actionSave_Settings.setObjectName("actionSave_Settings")
        self.actionHelpDoc = QtWidgets.QAction(FIITM)
        self.actionHelpDoc.setObjectName("actionHelpDoc")
        self.actionCopyright = QtWidgets.QAction(FIITM)
        self.actionCopyright.setObjectName("actionCopyright")
        self.actionOpen_ICPicture = QtWidgets.QAction(FIITM)
        self.actionOpen_ICPicture.setObjectName("actionOpen_ICPicture")
        self.actionOpen_ICVideo = QtWidgets.QAction(FIITM)
        self.actionOpen_ICVideo.setObjectName("actionOpen_ICVideo")
        self.actionVisit_Homepage_On_Github = QtWidgets.QAction(FIITM)
        self.actionVisit_Homepage_On_Github.setObjectName("actionVisit_Homepage_On_Github")
        self.actionSettings = QtWidgets.QAction(FIITM)
        self.actionSettings.setObjectName("actionSettings")
        self.actionAbout_Parameters = QtWidgets.QAction(FIITM)
        self.actionAbout_Parameters.setObjectName("actionAbout_Parameters")
        self.menuFile.addAction(self.actionOpen_DCPicture)
        self.menuFile.addAction(self.actionOpen_ICPicture)
        self.menuFile.addAction(self.actionOpen_DCVideo)
        self.menuFile.addAction(self.actionOpen_ICVideo)
        self.menuFile.addAction(self.actionSave_Log)
        self.menuFile.addAction(self.actionSave_Settings)
        self.menuSettings.addAction(self.actionSettings)
        self.menuSettings.addAction(self.actionAbout_Parameters)
        self.menuHelp.addAction(self.actionVisit_Homepage_On_Github)
        self.menuHelp.addAction(self.actionHelpDoc)
        self.menuHelp.addAction(self.actionCopyright)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(FIITM)
        QtCore.QMetaObject.connectSlotsByName(FIITM)

    def retranslateUi(self, FIITM):
        _translate = QtCore.QCoreApplication.translate
        FIITM.setWindowTitle(_translate("FIITM", "MainWindow"))
        self.label_2.setText(_translate("FIITM", "红外相机体温测量"))
        self.label_5.setText(_translate("FIITM", "数码相机："))
        self.RunDC_BT.setText(_translate("FIITM", "开始"))
        self.PauseDC_BT.setText(_translate("FIITM", "暂停"))
        self.label_6.setText(_translate("FIITM", "红外相机："))
        self.RunIC_BT.setText(_translate("FIITM", "开始"))
        self.PauseIC_BT.setText(_translate("FIITM", "暂停"))
        self.label_7.setText(_translate("FIITM", "截取视频："))
        self.SaveVideoStart_BT.setText(_translate("FIITM", "开始"))
        self.SaveVideoStop_BT.setText(_translate("FIITM", "暂停"))
        self.label_9.setText(_translate("FIITM", "自动保存关键帧："))
        self.AutosaveFramesStart_BT.setText(_translate("FIITM", "开始"))
        self.AutosaveFramesStop_BT.setText(_translate("FIITM", "暂停"))
        self.label_8.setText(_translate("FIITM", "截取当前帧："))
        self.SaveFrame_BT.setText(_translate("FIITM", "保存"))
        self.InputModeCameras_RBT.setText(_translate("FIITM", "相机"))
        self.InputModeVideos_RBT.setText(_translate("FIITM", "视频"))
        self.InputModePictures_RBT.setText(_translate("FIITM", "图片"))
        self.label.setText(_translate("FIITM", "数码相机人脸检测"))
        self.Exit_BT.setText(_translate("FIITM", "退出程序"))
        self.menuFile.setTitle(_translate("FIITM", "文件"))
        self.menuSettings.setTitle(_translate("FIITM", "设置"))
        self.menuHelp.setTitle(_translate("FIITM", "帮助"))
        self.actionOpen_DCPicture.setText(_translate("FIITM", "打开数字图像..."))
        self.actionOpen_DCVideo.setText(_translate("FIITM", "打开数字视频..."))
        self.actionSave_Log.setText(_translate("FIITM", "保存运行日志"))
        self.actionSave_Settings.setText(_translate("FIITM", "保存当前参数"))
        self.actionHelpDoc.setText(_translate("FIITM", "帮助文档..."))
        self.actionCopyright.setText(_translate("FIITM", "著作权(Copyright)..."))
        self.actionOpen_ICPicture.setText(_translate("FIITM", "打开红外图片..."))
        self.actionOpen_ICVideo.setText(_translate("FIITM", "打开红外视频..."))
        self.actionVisit_Homepage_On_Github.setText(_translate("FIITM", "访问项目Github主页..."))
        self.actionSettings.setText(_translate("FIITM", "参数设置..."))
        self.actionAbout_Parameters.setText(_translate("FIITM", "参数说明..."))

